name: MainpluginsRanks
version: ${project.version}
main: elo.mainplugins.ranks.MainpluginsRanks
api-version: '1.20'
depend: [MainpluginsCore]
softdepend: [MainpluginsQuests]

commands:
  "@setranga":
    description: Ustaw rangę graczowi (gracz/vip/admin)
    usage: /<command> <gracz> <gracz|vip|admin>
    permission: mainplugins.ranks.admin
    permission-message: "&cNie masz permisji do tej komendy!"
  "@ranga":
    description: Sprawdź rangę gracza
    usage: /<command> <gracz>
    permission: mainplugins.ranks.admin
    permission-message: "&cNie masz permisji do tej komendy!"
  "@reloadrangi":
    description: Wczytaj ranks-config.yml (wygląd rang) na nowo, bez restartu serwera
    permission: mainplugins.ranks.reload
    permission-message: "&cNie masz permisji do tej komendy!"

permissions:
  mainplugins.ranks.admin:
    description: Dostęp do nadawania/zmiany rang graczy
    default: op
  mainplugins.ranks.reload:
    description: Pozwala przeładować wygląd rang
    default: op
