name: MainpluginsSkyblock
version: ${project.version}
main: elo.mainplugins.skyblock.MainpluginsSkyblock
api-version: '1.20'
depend: [MainpluginsCore]
softdepend: [MainpluginsSpawn]

commands:
  is:
    description: Wyspa
    usage: "/is [menu|dom|ustawdom|ustawspawn|usun|granica|budowanie|pvp|potwory|ulepszenia|czlonkowie|zapros <gracz>|akceptuj|odrzuc|opusc|awansuj <gracz>|degraduj <gracz>|wyrzuc <gracz>|wplac <kwota>|wyplac <kwota>] - samo /is teleportuje do punktu z /is ustawspawn, /dom-/home zawsze do punktu z /is ustawdom (ang. aliasy: sethome/border/guests/mobs/upgrade/members/invite/accept/deny/leave/promote/demote/remove/deposit/withdraw)"
  dom:
    description: Teleport na wyspę - do punktu ustawionego przez "/is ustawdom" (niezależnego od "/is ustawspawn")
    aliases: [home]

permissions:
  mainplugins.skyblock.bypass:
    description: Pozwala przechodzić przez granice wysp bez ograniczeń ruchu
    default: op