name: MainpluginsSpawn
version: ${project.version}
main: elo.mainplugins.spawn.MainpluginsSpawn
api-version: '1.20'
depend: [MainpluginsCore]

commands:
  spawn:
    description: Teleportuj się na spawn (odradzasz się tam też po śmierci)
  "@setspawn":
    description: Ustaw główny punkt spawnu (miejsce teleportu)
    usage: "/@setspawn [info]"
    permission: mainplugins.spawn.admin
    permission-message: "&cNie masz permisji do tej komendy!"
  "@obszar":
    description: Zarządzaj chronionymi obszarami serwera (spawn, w przyszłości też warpy)
    usage: "/@obszar <wand|usun|lista|info|moby|border> <nazwa> ..."
    permission: mainplugins.spawn.admin
    permission-message: "&cNie masz permisji do tej komendy!"
  warp:
    description: Teleportuj się do nazwanego warpu (niektóre wymagają ukończenia questa)
    usage: "/warp <nazwa>"
  "@setwarp":
    description: Ustaw/nadpisz warp w swojej aktualnej lokalizacji
    usage: "/@setwarp <nazwa>"
    permission: mainplugins.spawn.admin
    permission-message: "&cNie masz permisji do tej komendy!"
  "@delwarp":
    description: Usuń istniejący warp
    usage: "/@delwarp <nazwa>"
    permission: mainplugins.spawn.admin
    permission-message: "&cNie masz permisji do tej komendy!"

permissions:
  mainplugins.spawn.admin:
    description: Pozwala zarządzać spawnem/obszarami/warpami (punkt, wand, moby) i omija ich ochronę przed budowaniem/niszczeniem
    default: op