name: MainpluginsCrates
version: ${project.version}
main: elo.mainplugins.crates.MainpluginsCrates
api-version: '1.20'
depend: [MainpluginsCore]

commands:
  "@crate":
    description: (Admin) Crates - give crates/keys, place crates in the world, list, reload
    usage: /<command> give <player> <crate> [amount] | key <player> <key> [amount] | place <crate> | remove | list | reload
    permission: mainplugins.crates.admin
    permission-message: "&cNie masz permisji do tej komendy!"

permissions:
  mainplugins.crates.admin:
    description: Access to /@crate
    default: op
