name: MainpluginsTeleport
version: ${project.version}
main: elo.mainplugins.teleport.MainpluginsTeleport
api-version: '1.20'

commands:
  teleportuj:
    description: Wyślij prośbę o teleportację do gracza
    usage: /<command> <gracz>
    aliases: [tp]
  tpakceptuj:
    description: Zaakceptuj prośbę o teleportację
    aliases: [tpaccept]
  tpodrzuc:
    description: Odrzuć prośbę o teleportację
    aliases: [tpdeny]