name: MainpluginsMenu
version: ${project.version}
main: elo.mainplugins.menu.MainpluginsMenu
api-version: '1.20'

commands:
  menu:
    description: Panel pomocy
  "@reloadmenu":
    description: Wczytaj menu-gui.yml na nowo, bez restartu serwera
    permission: mainplugins.menu.reload
    permission-message: "&cNie masz permisji do tej komendy!"

permissions:
  mainplugins.menu.reload:
    description: Pozwala przeładować układ Głównego Menu Serwera
    default: op
