name: MainpluginsAnnouncer
version: ${project.version}
main: elo.mainplugins.announcer.MainpluginsAnnouncer
api-version: '1.20'

commands:
  "@reloadannouncer":
    description: Wczytaj ogloszenia.yml na nowo, bez restartu serwera
    permission: mainplugins.announcer.reload
    permission-message: "&cNie masz permisji do tej komendy!"

permissions:
  mainplugins.announcer.reload:
    description: Pozwala przeładować konfigurację ogłoszeń
    default: op