name: MainpluginsTools
version: ${project.version}
main: elo.mainplugins.tools.MainpluginsTools
api-version: '1.20'
depend: [MainpluginsCore]

commands:
  "@addlvl":
    description: "[DEBUG] Dodaje poziomy trzymanemu narzedziu (testy)"
    usage: "/<command> [ilosc]"
    permission: mainplugins.tools.addlvl
    permission-message: "&cNie masz permisji do tej komendy!"
  "@dajwszystko":
    description: "[DEBUG] Nadaje Kilof Niflheim, wszystkie ewoluujace narzedzia i wszystkie gemy do testow"
    usage: "/<command> [gracz]"
    permission: mainplugins.tools.dajwszystko
    permission-message: "&cNie masz permisji do tej komendy!"
  "@reloadnarzedzia":
    description: "[ADMIN] Wczytuje ewoluujace-narzedzia.yml na nowo, bez restartu serwera"
    permission: mainplugins.tools.reloadnarzedzia
    permission-message: "&cNie masz permisji do tej komendy!"

permissions:
  mainplugins.tools.addlvl:
    description: Pozwala levelowac trzymane narzedzie do testow
    default: op
  mainplugins.tools.dajwszystko:
    description: Pozwala nadac komplet wszystkich kilofow i gemow do testow
    default: op
  mainplugins.tools.reloadnarzedzia:
    description: Pozwala przeladowac ewoluujace-narzedzia.yml
    default: op
